### ISSUE TITLE
Huddle notes and next step (2016-01-10)

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#23]
Great discussion today with @cityhubla, @maning @jschleuss! 

We agreed to **move ahead with the process** and for the first stage of import, we will focus on **building geometry and building types**.  Due to issues with address data, we will punt this for now and probably import as nodes in later stages (*sidenote: [LA County address is already in openaddres.io](https://github.com/openaddresses/openaddresses/blob/273a99c9c13776455c9bf71f5969fdaaadee69be/sources/us/ca/los_angeles.json)*).

**Next steps**

- [x] Verify projection information of building footprint from LA County contacts and find ways to script issues on shift/offset #18#issuecomment-167976124 and non-orthogonal buildings #22  @jschleuss
- [x] Update sample data that includes conflated building geometry to building type based on assessor information for review #14 @jschleuss
- [x] Review and update [import instructions](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md) #10 @cityhubla @maning
- [x] Prepare a TM project and run a test import using [OSM dev API](wiki.openstreetmap.org/wiki/Using_the_dev_server). Improve docs and script if needed after the test run. @maning
- [x] Once all the :arrow_double_up:  issues are resolved, inform relevant community mailinglists of our plan and solicit feedback #1. @almccon @maning
- [x] Start import in stages (first, LA City, then move to the next city).  We exclude Pasadena due to data issues  #20.
- [x] Organize mapathons via Maptime to help in the import process. @cityhubla @jschleuss

**Others**
Talk to LA County gov about the possibility to receiving data changes from OSM [similar to NYC](https://github.com/osmlab/changewithin). @cityhubla

**Comment by bondah** [comment]
Hi guys! Just wondering if the current building import happening for LA on OSM is affiliated with this group? It looks like it is being done Mapbox staff.

**Comment by jschleuss** [comment]
@bondah They're not affiliated. That other group is tracing. Trying to reach out to keep them from doing more. The building file has better data on it and could be more accurate than tracing.

**Comment by cityhubla** [comment]
Looks like we hit the next steps with import stages and mapathon, closing issue
